version: '3.8'

services:
  wsl-cuda:
    image: template:latest
    container_name: template
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [gpu]
    working_dir: /root/workspace
    volumes:
      - ./workspace:/root/workspace  # ホームディレクトリに"workspace"フォルダをマウント
    ports:
      - "80:80"
      - "443:443"
      - "20000:20000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    command: /bin/bash
    stdin_open: true
    tty: true